### ISSUE TITLE
drmi filters out too many images

### ISSUE THREAD

**Issue by tstelzer** [MartinRamm/fzf-docker#8] opened 2019-12-05 16:39 UTC
As discussed in person:
Expected: When running `drmi`, I expect to see _all_ images, including those without tags.
Actual: I only see those images with tags. Which makes it hard to get rid of cruft images.

**Comment by MartinRamm** [comment] 2020-09-20 18:39
Hey @tstelzer,

The way this is implemented right now is that when you remove an image with `drmi`, it removes those "cruft images" (docker calls them "dangling") you are talking about<sup>[1](#myfootnote1)</sup>. So this isn't the cause of the problem.

Further reading the documentation<sup>[2](#myfootnote2)</sup>, if the image you are trying to remove an image that has multiple tags, only the tag gets removed. Since we are first resolving the tag's image id in the `drmi` command<sup>[3](#myfootnote3)</sup>, this also shouldn't cause an issue. I decided to add a warning about this into the readme though (3e0146e).

Further reading the documentation, images that you pull an image with a digest reference, it won't have a tag. So in `fzf` they will be displayed something like this: `selenium/node-chrome:<none>`. This breaks the logic and may be a potential cause of this bug. Will be fixed in the associated pr (6bda090).

Also, if you build an image without providing a tag (using the `-t` or `--tag` param with `docker build`), it will be considered a dangling image (as no tag exists). I am not aware of any way to access the build context (folder name/url - basically I mean here the argument given to `docker build`). I am currently exploring options on how to add options about dangling images. Will keep you posted.

**Footnotes:**
<a name="myfootnote1"><sup>1</sup></a>: [Source code of `drmi`/`drmia`](https://github.com/MartinRamm/fzf-docker/blob/1.1.2-beta/docker-fzf#L347-L354) does not include `--no-prune`, which, according to the [documentation](https://docs.docker.com/engine/reference/commandline/rmi/#options), should remove them.
<a name="myfootnote2"><sup>2</sup></a>: https://docs.docker.com/engine/reference/commandline/rmi/#extended-description
<a name="myfootnote3"><sup>3</sup></a>: https://github.com/MartinRamm/fzf-docker/blob/1.1.2-beta/docker-fzf#L346

**Comment by MartinRamm** [comment] 2020-09-21 20:33
As part of this ticket I decided to completely rework the `drmi` command in the following way, please ignore my previous comment:
* If an image has multiple tags, the current version shows each tag on a new line. Now, all tags are shown together on one line, together with the digest(s). e.g.: `my-image:latest (aliases: my-image:1.0.0, my-image@sha256:a3d2...)`. This avoids the change in the README and makes what is happening much clearer.
* You now have the option to remove all dangling images via a new entry: `All dangling images (total of 140)`
* If you are using labels during the build process, you may also distinguish dangling images via labels. Lets assume you add a label `name=my-service` to a dockerfile and build it 10 times. You now have two new options:
  * `All dangling images (total of 10) with the label name:my-service`
  * `All EXCEPT THE NEWEST dangling images (total of 9) with the label name:my-service`

will create a PR with these changes in a few moments

**Closed as completed** 2020-09-22 20:19 UTC
Labels: bug
